In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [15]:
import numpy as np
import tensorflow as tf

In [16]:
m1 = [[1.0, 2.0],
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0], 
               [3.0, 4.0]])
m3 = tf.constant([[1.0, 2.0],
                  [3.0, 4.0]])

In [17]:
m1

[[1.0, 2.0], [3.0, 4.0]]

In [18]:
m2 = tf.convert_to_tensor(m2, dtype=tf.float32)
m2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [19]:
m3 = tf.constant([ [[1, 2], [3, 4], [5, 6]],
                   [[7, 8], [9, 10], [11, 12]] ], 
                dtype=tf.float64, name='foo')

In [20]:
print(m3)

tf.Tensor(
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]], shape=(2, 3, 2), dtype=float64)


In [38]:
# Ex 2.2 - Gaussian Dist
mean = 0.0
sigma = 1.0
x = tf.constant([1, 2, 3], dtype=tf.float32)
(tf.exp(tf.negative(tf.pow(x - mean, 2.0) / (2.0 * tf.pow(sigma, 2.0) ))) *
(1.0 / (sigma * tf.sqrt(2.0 * np.pi))))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.24197073, 0.05399097, 0.00443185], dtype=float32)>

In [32]:
(1 / (sigma * tf.sqrt(2.0 * np.pi)))

<tf.Tensor: shape=(), dtype=float32, numpy=0.3989423>